/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BookComponent: typeof import('./components/Book/Component.vue')['default']
    BookList: typeof import('./components/Book/List.vue')['default']
    Box: typeof import('./components/Global/Box.vue')['default']
    FormField: typeof import('./components/Form/Field.vue')['default']
    IconBiZoomIn: typeof import('~icons/bi/zoom-in')['default']
    IconBiZoomOut: typeof import('~icons/bi/zoom-out')['default']
    IconMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IconMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiFileDownloadOutline: typeof import('~icons/mdi/file-download-outline')['default']
    IconMdiHelp: typeof import('~icons/mdi/help')['default']
    IconMdiImage: typeof import('~icons/mdi/image')['default']
    IconMdiLink: typeof import('~icons/mdi/link')['default']
    IconMdiLoading: typeof import('~icons/mdi/loading')['default']
    IconMdiPackageVariantClosedPlus: typeof import('~icons/mdi/package-variant-closed-plus')['default']
    IconMdiText: typeof import('~icons/mdi/text')['default']
    IconMdiVideo: typeof import('~icons/mdi/video')['default']
    IconMdiVolume: typeof import('~icons/mdi/volume')['default']
    IconPhBookThin: typeof import('~icons/ph/book-thin')['default']
    LayoutAuth: typeof import('./components/Layout/Auth.vue')['default']
    LayoutBackground: typeof import('./components/Layout/Background.vue')['default']
    LayoutDefault: typeof import('./components/Layout/Default.vue')['default']
    LayoutFooter: typeof import('./components/Layout/Footer.vue')['default']
    LayoutHeader: typeof import('./components/Layout/Header.vue')['default']
    LayoutIcon: typeof import('./components/Layout/Icon.vue')['default']
    LayoutLogo: typeof import('./components/Layout/Logo.vue')['default']
    Loading: typeof import('./components/Global/Loading.vue')['default']
    PAvatar: typeof import('primevue/avatar')['default']
    PButton: typeof import('primevue/button')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMenu: typeof import('primevue/menu')['default']
    PPassword: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
